/* this page was generated by Claude. 
It contains commands to open things because I'm too lazy to do that manually :)*/
import { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { ALL_FILES } from './Explorer';
import { THEMES } from './Themes';
import { useWorkspace } from './WorkspaceContext';

export default function CommandPalette() {
  const w = useWorkspace();
  const [q, setQ] = useState('');
  const [idx, setIdx] = useState(0);
  const listRef = useRef(null);
  const close = () => w.setPaletteOpen(false);

  const all = [
    { group: 'COMMANDS', label: 'Toggle Terminal', hint: 'Ctrl+`', run: w.toggleTerminal },
    { group: 'COMMANDS', label: 'Toggle Sidebar', hint: 'Ctrl+B', run: w.toggleSidebar },
    { group: 'COMMANDS', label: 'Download Resume', run: w.downloadCV },
    { group: 'COMMANDS', label: 'Toggle Fullscreen', run: w.toggleFullscreen },
    ...THEMES.map((t) => ({ group: 'COMMANDS', label: `Theme: ${t.label}`, run: () => w.setTheme(t.id) })),
    ...ALL_FILES.map((f) => ({ group: 'FILES', label: f.name, icon: f.icon, run: () => w.openFile(f.name) })),
  ];
  const needle = q.toLowerCase().replace(/^>\s*/, '');
  const items = all.filter((i) => i.label.toLowerCase().includes(needle));

  useEffect(() => {
    listRef.current?.querySelector('.active')?.scrollIntoView({ block: 'nearest' });
  }, [idx]);

  const run=(item) => { if (!item) return; close(); item.run(); };

  const onKey = (e) => {
    if (e.key === 'ArrowDown') { e.preventDefault(); setIdx((i) => (i + 1) % Math.max(items.length, 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setIdx((i) => (i - 1 + items.length) % Math.max(items.length, 1)); }
    else if (e.key === 'Enter') run(items[idx]);
    else if (e.key === 'Escape') close();
  };

  return (
    <motion.div className="palette-backdrop" onClick={close} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
      <motion.div
        className="palette"
        onClick={(e) => e.stopPropagation()}
        initial={{ y: -16, opacity: 0, scale: 0.98 }}
        animate={{ y: 0, opacity: 1, scale: 1 }}
        exit={{ y: -16, opacity: 0 }}
        transition={{ duration: 0.18 }}
      >
        <input autoFocus value={q} placeholder="Go to file or run command..." onChange={(e) => { setQ(e.target.value); setIdx(0); }} onKeyDown={onKey} />
        <div className="palette-list" ref={listRef}>
          {items.length === 0 && <div className="palette-group">No matching results</div>}
          {items.map((it, i) => (
            <div key={it.group + it.label}>
              {(i === 0 || items[i - 1].group !== it.group) && <div className="palette-group">{it.group}</div>}
              <div className={`palette-item ${i === idx ? 'active' : ''}`} onMouseEnter={() => setIdx(i)} onClick={() => run(it)}>
                {it.icon}<span>{it.label}</span>{it.hint && <span className="hint">{it.hint}</span>}
              </div>
            </div>
          ))}
        </div>
        <div className="palette-foot">↑↓ navigate · ↵ open · Esc close</div>
      </motion.div>
    </motion.div>
  );
}