/* this page was generated by Claude. 
It contains commands to open things because I'm too lazy to do that manually :)*/

import { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { VscClose } from 'react-icons/vsc';
import { ALL_FILES } from './Explorer';
import { THEMES } from './Themes';
import { useWorkspace } from './WorkspaceContext';

const PROMPT = 'mohamed@portfolio:~$';
const BANNER = "Mohamed Ferchichi's portfolio terminal\nType 'help' to see what I can do.\n";
const HELP = `Available commands:
  help            show this list
  whoami          who am I
  ls              list files
  open <file>     open a file (ex: open about)
  skills          my tech stack
  projects        what I built
  contact         how to reach me
  cv              download my resume
  theme [name]    list or change the theme
  neofetch        system info
  date, echo, clear, exit`;

export default function TerminalPanel() {
  const w = useWorkspace();
  const [tab, setTab] = useState('terminal');
  const [lines, setLines] = useState([{ out: BANNER }]);
  const [value, setValue] = useState('');
  const [hist, setHist] = useState([]);
  const [hi, setHi] = useState(-1);
  const inputRef = useRef(null);
  const bodyRef = useRef(null);

  useEffect(() => { inputRef.current?.focus(); }, [tab]);
  useEffect(() => { if (bodyRef.current) bodyRef.current.scrollTop = bodyRef.current.scrollHeight; }, [lines, tab]);

  const exec = (raw) => {
    const [cmd = '', ...rest] = raw.trim().split(/\s+/);
    const arg = rest.join(' ');
    switch (cmd.toLowerCase()) {
      case '': return '';
      case 'help': return HELP;
      case 'whoami': return 'Mohamed Ferchichi · Big Data student @ ISAMM · looking for a PFE internship';
      case 'ls': return ALL_FILES.map((f) => f.name).join('   ');
      case 'open': case 'cat': {
        const f = ALL_FILES.find((x) => x.name.toLowerCase().startsWith(arg.toLowerCase()));
        if (!arg || !f) return `usage: open <file>   (try: ls)`;
        w.openFile(f.name);
        return `opening ${f.name}...`;
      }
      case 'skills': return 'Languages : Python, Java, C, R\nML        : pandas, NumPy, Matplotlib, PyTorch, scikit-learn\nWeb       : HTML, CSS, JavaScript, PHP, React\nDatabases : MySQL, Firebase, MongoDB\nTools     : Linux, Git, Android Studio';
      case 'projects': return '- Digit Recognition\n- Student Performance Analysis\n- Neural Network From Scratch\n- Portfolio (VS Code theme)\n- Bablio App\n- Bondin Coffee';
      case 'contact': return 'email   : hama.ferchichi@gmail.com\ngithub  : github.com/moohameedd\nlinkedin: linkedin.com/in/mohamed-ferchichi';
      case 'cv': w.downloadCV(); return 'downloading CV_Mohamed_Ferchichi_EN.pdf ...';
      case 'theme': {
        if (!arg) return THEMES.map((t) => `${t.id}${t.id === w.theme ? '  (current)' : ''}`).join('\n');
        const t = THEMES.find((x) => x.id === arg.toLowerCase() || x.label.toLowerCase().includes(arg.toLowerCase()));
        if (!t) return `theme not found: ${arg}`;
        w.setTheme(t.id);
        return `theme set to ${t.label}`;
      }
      case 'neofetch': return 'mohamed@portfolio\n-----------------\nOS     : Linux (Ubuntu)\nShell  : zsh... well, this fake one\nEditor : VS Code (kind of)\nStack  : React, Python, Big Data\nTyping : 81 WPM';
      case 'date': return new Date().toString();
      case 'echo': return arg;
      case 'sudo': return 'nice try. This incident will be reported.';
      case 'exit': w.setTerminalOpen(false); return '';
      default: return `command not found: ${cmd}. Type 'help'.`;
    }
  };

  const submit = () => {
    const raw = value;
    setValue(''); setHi(-1);
    if (raw.trim()) setHist((h) => [raw, ...h]);
    if (raw.trim().toLowerCase() === 'clear') { setLines([]); return; }
    const res = exec(raw);
    setLines((l) => [...l, { in: raw }, ...(res ? [{ out: res }] : [])]);
  };

  const onKeyDown = (e) => {
    if (e.key === 'Enter') submit();
    else if (e.key === 'ArrowUp') { e.preventDefault(); const n = Math.min(hi + 1, hist.length - 1); if (hist[n] !== undefined) { setHi(n); setValue(hist[n]); } }
    else if (e.key === 'ArrowDown') { e.preventDefault(); const n = hi - 1; setHi(n); setValue(n >= 0 ? hist[n] : ''); }
    else if (e.ctrlKey && e.key.toLowerCase() === 'l') { e.preventDefault(); setLines([]); }
  };

  return (
    <motion.div className="terminal" initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} transition={{ duration: 0.22, ease: 'easeInOut' }}>
      <div className="term-inner">
        <div className="term-head">
          {['terminal', 'problems', 'output'].map((t) => (
            <button key={t} className={`term-tab ${tab === t ? 'on' : ''}`} onClick={() => setTab(t)}>{t.toUpperCase()}</button>
          ))}
          <button className="term-close" onClick={() => w.setTerminalOpen(false)} title="Close panel"><VscClose /></button>
        </div>

        <div className="term-body" ref={bodyRef} onClick={() => inputRef.current?.focus()}>
          {tab === 'terminal' && (
            <>
              {lines.map((l, i) => l.in !== undefined
                ? <div key={i}><span className="term-prompt">{PROMPT}</span>{l.in}</div>
                : <pre key={i} className="term-out">{l.out}</pre>)}
              <div className="term-row">
                <span className="term-prompt">{PROMPT}</span>
                <input ref={inputRef} value={value} onChange={(e) => setValue(e.target.value)} onKeyDown={onKeyDown} spellCheck={false} autoComplete="off" />
              </div>
            </>
          )}
          {tab === 'problems' && <pre className="term-out">✓ No problems have been detected in the workspace.</pre>}
          {tab === 'output' && <pre className="term-out">{'[info] Compiled successfully\n[info] Theme: ' + w.theme + '\n[info] Ready on localhost:3000'}</pre>}
        </div>
      </div>
    </motion.div>
  );
}
